name: Hello world
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull request:
    branches:
      - main    

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "A Build stage"
  