name: context variable demo
on: push
jobs:
  context_demo:
    runs-on: ubuntu-latest
    steps:
      - name: use contect variables
        run: |
          echo " This workflow triggred by ${{github.actor}}"
          echo " The repository name is ${{github.repository}}"
          echo " The branch is ${{github.ref_name}}"
      - name: To print all the Github context variables
        run: echo " ${{toJson(github)}}"
      - name: Print all variables in Github
        run: printenv
      - name: Print Environment variables
        run: echo "$GITHUB_SHA"
    
