name: multiple jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build phase
        run: echo "Build Phase"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test case
      run: echo "Running test case"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy a app"
      - 
      - 
  
