name: outputs sharing the data between steps
on: push
jobs:
  Build:
    outputs:
      version: ${{steps.step1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Deploying the app with version ${{needs.Build.outputs.version}}
      
